### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by shujaatak** [edbee/edbee-app#3] opened 2019-11-24 07:41 UTC
App crashes with following information:

```
edbee-app\debug\edbee.exe ...
 WARN 12:38:47.202 "textgrammar.cpp" @ 306 "Error reading file C:/Qt/elbee/build-edbee-app-Desktop_Qt_5_13_2_MinGW_64_bit-Debug/edbee-app/debug/data/syntaxfiles/C#.tmLanguage:line 155: Name or scope is empty. Cannot parse language!" 
12:38:50: The program has unexpectedly finished.
12:38:50: The process was ended forcefully.
```

**Comment by gamecreature** [comment] 2019-11-25 05:00
Hi @shujaatak, The textgrammer warning isn't the cause of the crash. (There's a strange rule in the c# grammer). It does that by default.
Do you have more information about the crash? A stacktrace ?

**Comment by gamecreature** [comment] 2024-10-08 17:54
I'm closing this issue, it's very old and no new information has been given.

**Closed as completed by gamecreature** 2024-10-08 17:54 UTC
